### ISSUE TITLE
Custom date ranges for perf page

### ISSUE THREAD

**Issue by mayfield** [SauceLLC/sauce4strava#100]
Use calendar inputs to offer custom date ranges.

**Comment by dvvilkins** [comment]
Agreed, or at least offer a 6 week option so we can look at the 42-week window on which CTL is based. Right now, there's only 4 and 12 week views.

**Comment by mayfield** [comment]
@dvvilkins Not a solution but as a hack you can write in any number in the url and hit enter.  like ..

https://www.strava.com/sauce/performance/fitness/139587/6/weeks

Replace my strava ID with yours, or just edit the number and metric;  weeks, months, and years are supported.

**Comment by dvvilkins** [comment]
That's solution enough for me. Thanks Justin!

**Comment by mayfield** [comment]
Another user request for this ...

> You can select a time range (both in the fitness tracking tab as the peak performances. The suggestion, or question: Is it possible to select a calender year, the years you do have activities logged toe Strava e.g. 2022, 2021,2020 ? So you can track your peak performances or fitness lever over different years?

**Comment by mayfield** [comment]
Implemented as of v8.7.0: click the start or end date to select a custom value from a calendar.
