### ISSUE TITLE
Activities table empty

### ISSUE THREAD

**Issue by MrSpock77** [SauceLLC/sauce4strava#107]
I have added a new panel of type "Activities Table", but the table is completely empty. All my activities are synchronized. The table is also empty for other athletes I follow. "Fitness Tracking" or "Peak Performances" doesn't matter.

Browser: Firefox 99.0

**Comment by mayfield** [comment]
Interesting.

Firefox doesn't load urls with `path//path2` when the extension is packaged.  Debug loaded extensions it works fine and other browsers too.  Fun one!  Easy fix, but I'l have to wait for the FF store gods to approve it.  Sometimes they are insane.
