### ISSUE TITLE
"Missing TSS" links not working

### ISSUE THREAD

**Issue by MrSpock77** [SauceLLC/sauce4strava#109]
Nothing happens when I click on the "Missing TSS" links in the Training panel.

Browser: Firefox 99.0

(I am not sure if that is the same problem as resolved in #107.)

**Comment by mayfield** [comment]
Yeah, same code and templates affected this one.  The firefox store updated late yesterday, so you should be able to update and resolve both of these.

**Comment by MrSpock77** [comment]
Thanks, it works! I really appreciate your work.
