### ISSUE TITLE
Use accurate weight

### ISSUE THREAD

**Issue by metyl** [SauceLLC/sauce4strava#11]
Strava stores weight with two digits precision e.g. `74.91`, can this weight be presented and used to W/kg calculations?

**Comment by mayfield** [comment]
+1  Will look into this this week.

Cheers!

**Comment by mayfield** [comment]
Looks like the weight is always stored without rounding and when used for w/kg it is not using the rounded value.  The presentation of the weight is however rounded to the nearest whole number.  For imperial numbers this isn't that big a deal but kg it's probably more annoying.  I'll change the presentation to include 1 decimal place of precision in the presentation.

**Comment by mayfield** [comment]
Fixed
