### ISSUE TITLE
Challenges showing up in feed.

### ISSUE THREAD

**Issue by norbsy** [SauceLLC/sauce4strava#112]
I noticed a bunch of challenges showed up for the first time in a long time today.

https://i.imgur.com/dQSd7oN.png

https://imgur.com/texfyOO

**Comment by mayfield** [comment]
Hi @norbsy this is probably related to #101.  Are you on v8.0.8?   It just went out for chrome this afternoon, so you may need to force an update.

**Comment by norbsy** [comment]
> Hi @norbsy this is probably related to #111 1. Are you on v8.0.8? It just went out for chrome this afternoon, so you may need to force an update.

Thank you. Sorry if this is a duplicate, I didnt think to search in all threads. Github isnt friendly to idiots like me  :)

**Comment by mayfield** [comment]
No worries.  #111 doesn't really describe your exact problem but they are both tied to an upstream Strava change.  Let me know if 8.0.8 works for you and I'll close this.

**Comment by norbsy** [comment]
> No worries. #111 doesn't really describe your exact problem but they are both tied to an upstream Strava change. Let me know if 8.0.8 works for you and I'll close this.

Indeed it did. Shut down Brave and restarted and all good. Thanks for the speedy reply.

**Comment by mayfield** [comment]
Great, thanks!
