### ISSUE TITLE
Incorrect intensity calculation for multiple rides

### ISSUE THREAD

**Issue by dvvilkins** [SauceLLC/sauce4strava#114]
The Daily Summary in the Activity Details (right rail of Fitness Tracking) incorrectly calculates IF when there are multiple activities on the same day. I've pasted an example for a day containing two activities, with an IF of 63% and 65% each. The daily summary therefore should be somewhere between the two (64% ish, however it shows 93%. 

<img width="262" alt="image" src="https://user-images.githubusercontent.com/20048187/166572683-9056b16d-965f-474b-bc84-42729a947ace.png">

**Comment by mayfield** [comment]
Nice catch.
