### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by Santi-Nieva** [SauceLLC/sauce4strava#115]
Hi, I have been a patron for sauce for strava for 2 months now. This morning i can only access the free features and it is asking me to become a patron. However, i can see that on the 3rd of May a new payment went in so I guess I should have all the features available. please could you help me to recover my patron account?

Thank you

Santi

**Comment by mayfield** [comment]
Hi @Santi-Nieva 

Can you try relinking to patreon using this link: https://www.saucellc.io/patreon-oauth

If that doesn't work, send me an email to support@saucellc.io  and I'll get your squared away.

**Comment by Santi-Nieva** [comment]
Thanks a lot. All sorted now.
Santi
    On Saturday, May 7, 2022, 09:32:04 AM GMT+1, Justin Mayfield ***@***.***> wrote:  
 
 


Closed #115.
