### ISSUE TITLE
Activity title changes not updated

### ISSUE THREAD

**Issue by MrSpock77** [SauceLLC/sauce4strava#116]
When an athlete changes the title of an activity after it has been imported, Sauce still shows the original title. I have tried to reimport the activity, but the title remains unchanged. Is it be possible to update the title in the database every time an activity is opened in the browser? Otherwise, let the reimport feature update the title.

**Comment by mayfield** [comment]
I actually do have code for this that should be updating type, name and description when you visit the analysis page for an activity.  Just to double check, you're visiting the `/activities/<id>` page for the activity in question (waiting at least 2 seconds too) and then when going back to Sauce Performance it's still the old meta data?

**Comment by mayfield** [comment]
https://github.com/SauceLLC/sauce4strava/blob/3dabe4dce0cca2a1efe8ac9375f7168f3e30f801/src/site/analysis.js#L3229-L3259

**Comment by MrSpock77** [comment]
Yes, i am visiting `/activities/<id>`, but the Activities Table is not updated.

Browser: Firefox 100.0
Sauce: 8.0.8

**Comment by mayfield** [comment]
Must be a regression then.  I'll have a look.

Thank you.

**Comment by mayfield** [comment]
@MrSpock77 one more question.  If you restart FireFox is the meta data updated?  I have a pretty complicated database caching system and if the restart affects this, then I've got a bug there.

**Comment by MrSpock77** [comment]
No
