### ISSUE TITLE
Themes/Dark Mode broken in Firefox

### ISSUE THREAD

**Issue by mostafamossaad** [SauceLLC/sauce4strava#123]
Hello. Sorry if I'm reopening this (I checked #118 )
System preferences (My settings) and dark mode don't seem to be working for me.
The top bar, for example, turns from white to a more "sauce" like color.
Thank you.

**Comment by mayfield** [comment]
Hi @mostafamossaad 

Can you attach a screencap?  Mine still looks okay (to me)..

![image](https://user-images.githubusercontent.com/139316/177639059-80d0c4e7-f672-48cf-b2be-33e285894970.png)


Sometimes Strava rolls out site changes very slowly and it can take a week or two to reach all users, so you might have a new version of that page that I'm not seeing yet.

**Comment by mostafamossaad** [comment]
Hi Justin,
Yours look OK than mine :)
________________________________

**Comment by mostafamossaad** [comment]
I thought I already did.
One. More. Time.
________________________________

**Comment by mayfield** [comment]
@mostafamossaad Looks like you might need to use the GitHub web interface instead of an email attachment.

**Comment by mostafamossaad** [comment]
![Capture](https://user-images.githubusercontent.com/3321793/178067810-1c9dd458-bb01-448f-92cb-4e5c3b2f176e.PNG)
The third time should be a charm :)

**Comment by mostafamossaad** [comment]
Hi @mayfield . I was looking into Strava today and it was dark and I thought I'd tell you.
I hadn't realized this was closed as completed 14 days ago (I wasn't having dark mode all this time).
What about the maps though? Can they be "normal" even within the dark view?
Thanks

**Comment by mayfield** [comment]
Hi @mostafamossaad the Firefox release with that patch went out yesterday.  There is no mechanism to revert the maps as of now, but I'll consider it for the future.

**Comment by mostafamossaad** [comment]
Thanks. Good luck
