### ISSUE TITLE
patron at $2 but not working

### ISSUE THREAD

**Issue by 1cavr** [SauceLLC/sauce4strava#124]
sorry don't know how else to contact u. i've been patron for a couple of months at first i was able to see the Fitness Tracking and Peak Performances but now it just kicks me to a screen that says I need to be a patron to access. When i click on that it shows that i'm a patron and i'm being billed at $2 but i can't access all those features. what do i do?

**Comment by mayfield** [comment]
Hi @1cavr sounds like it just got unlinked.  Click on the "Link with patreon" link in the options panel or just click here from the browser you use sauce on, https://saucellc.io/patreon-oauth

**Comment by 1cavr** [comment]
did that... now it's showing me nothing when i click on Fitness Tracking and Peak Perf ...  BTW, this problem is when i'm using my firefox browser... 

this morn i started enabling sauce on Chrome and it looks like its connected and loading in my history for the analytics pages. i sure would like to get firefox solved tho as its my preferred browser... thx for any guidance.

**Comment by mayfield** [comment]
@1cavr Let's pick this up via email.  Can you send me message with a screencap of what you're seeing in FF to support@saucellc.io?
