### ISSUE TITLE
When viewing a run segment, the sauce tool push the bottom few options off the page

### ISSUE THREAD

**Issue by sselfridge** [SauceLLC/sauce4strava#130]
The sauce Tools are making the div taller than strava's CSS allows for.  Had to go to the div with class sauce-btn-group and set it to display:none to view a comparison for a running segment.

With Sauce:
![image](https://user-images.githubusercontent.com/44272343/184433834-207cd276-ca93-4fc0-80b8-61fce7171793.png)

With out Sauce:
![image](https://user-images.githubusercontent.com/44272343/184433860-c77ff4c5-82eb-49f1-8c8a-557e6ce1ecb2.png)

**Comment by mayfield** [comment]
Hi @sselfridge 

Fix is in, but wanted to mention you might like the "Use detailed run segments" option, which isn't affected by this and is better IMO.  Also if you're not a patreon you can hide those buttons with the "Hide Sauce bonus features" option too.

**Comment by sselfridge** [comment]
@mayfield thanks for the quick fix! I'll look into that detailed run but, not used to running Strava much.  Cheers
