### ISSUE TITLE
peak power skewed by paused tracks

### ISSUE THREAD

**Issue by dunqdunq** [SauceLLC/sauce4strava#132]
I have several instances where my peak results at 1 min, 2 min etc are skewed because I was stopped at the lights, and then took off quick.  This example screenshot shows the 490W over 2min where data is missing for the first 1m20s there.

![Screenshot 2022-08-18 10 39 53](https://user-images.githubusercontent.com/111495667/185353574-560eb77e-1a04-477f-9de2-aa21505d7e96.png)

**Comment by mayfield** [comment]
Hi @dunqdunq can you send me the url with that analysis selection?

**Comment by dunqdunq** [comment]
https://www.strava.com/activities/7657491836/analysis/733/782

**Comment by mayfield** [comment]
Cleaning up old issue.  Reopen with URL of offending activity (previous one is down) if still valid.
