### ISSUE TITLE
Major Rubberbanding

### ISSUE THREAD

**Issue by MarcelMoes** [SauceLLC/sauce4strava#133]
Hi,

I just tried a pace partner ride on zwift and turned on Sauce. As soon as it came on I experienced some major rubberbanding on the screen. Turned it of and rubberbanding dissappeared. 
I have a strong enough pc system and I usually never experience rubberbanding. 
The ride was on Wandering Flats Makuri with coco pace partner.

Love the UI layout however not the rubberbanding.

Any ideas on what could be causing it?

Thanks 

BR 

Marcel

**Comment by mayfield** [comment]
Hi @MarcelMoes, just to clarify what you mean by rubberbanding.  This is the behavior seen in meetups where your group sticks together.  But you were observing your avatar being stuck to the pace partner?  Or some other sort of performance degredation?

In either case, it might be helpful to examine your sauce logs and the zwift logs.  If you can attach them here, I'll see what I can figure out.

**Comment by MarcelMoes** [comment]
Hi Justin,
Rubberbanding is a graphics issue that happens at a certain framerate as I have understood from people more knowledgable than me. What happens is it looks like the avatar is being pushed and then pulled back and forth. I have recorded a short video of it happening while using Sauce. However I didn't have the Sauce overlay on OBS so it isn't showing. I will attach my Zwift log as well. I am not sure where to locate the Sauce log.  I usually don't have any issues with rubberbanding at all.  I checked task manager to see if there was any unusual load on the cpu, but nothing above 20%. 
I also tried with another pace partner where the group riding a long was smaller than with the pace partner where the rubberbanding occured. There was no rubberbanding when riding in the smaller group.  

My setup is Intel i3-12100f 16gb Ram, Nvidia geforce 1060-6gb , Asus VG279q1A monitor with Adaptive Sync.

It might be one off issue, but I will try to see what happens if I try pace partners in watopia or even in a race.

Video of rubberbanding:  https://www.dropbox.com/s/2246ad81kb8fe1n/2022-09-27%2011-43-42.mkv?dl=0
Zwift log file when riding with bigger group pace partner COCO :[Log.txt](https://github.com/SauceLLC/sauce4strava/files/9654901/Log.txt)

Zwift log file when riding with smaller group and no rubberbanding occruring:  
[Log (old 1).txt](https://github.com/SauceLLC/sauce4strava/files/9654916/Log.old.1.txt)

**Comment by MarcelMoes** [comment]
Hi Justin,

I have done some more riding today. Did a pace partner ride in Watopia with Sauce on and did not experience any problems.
I also did a 45minute race in Watopia with Sauce on and again did not experience any problems. To finish of I did a 10minute ride with Coco pacepartner on Wandering Flats, the same route where the rubberbanding happened and also here I did not experience any rubberbanding. 
It looks to have been a one of issue.
I will of course report if I experience it again.

Thanks,

best regards 

Marcel

**Comment by mayfield** [comment]
Your ears must have been burning, I was just analyzing your logs!

**Comment by mayfield** [comment]
So those logs look pretty clean.  Really clean actually.  I've not experimented with this personally, but your zwift frame rate is probably higher than it needs to be.  Unless you're running a gaming monitor you probably won't notice much different above 60fps.  You could set the FPS cap for Zwift in the Nvidia tools to like 65fps and it might provide some headroom to avoid any lag.  Just a thought.

I'll close this for now, please hit me up at support@saucellc.io if it happens again.
