### ISSUE TITLE
New Activities Won't Sync

### ISSUE THREAD

**Issue by fernrees** [SauceLLC/sauce4strava#135]
For roughly the last 3 weeks my activities won't sync to Sauce despite being in strava.  I've tried manually syncing but it still doesn't update.  
![image](https://user-images.githubusercontent.com/8032128/196050441-2425d00a-712e-4936-8faa-fd2f6b214ce6.png)

**Comment by mayfield** [comment]
Hi @fernrees Few questions: 

Is this your profile or another users?

Can you send a pic of the sync panel?

If you right click -> Inspect and navigate to the console tab, do you see any errors or warnings?

If you're super technical I have one more thing that would be very useful to see, which is the console output from the Sauce "background" page.  I'll put the brief instructions here but if it's too much, don't worry about it just yet.

  Go to the main browser menu (three vertical dots usually)  -> More Tools -> Extensions

  Then enable developer mode using the top right toggle.

  Find Sauce for Strava and click on the "Inspect views
pages/bg.html" link.

  This opens a new devtools window.  Navigate to the console tab and then either send me the logs you see there or if it is clean initiate a sync manually from another window and then see if that generated any useful log messages.

Thank you @fernrees
