### ISSUE TITLE
Sauce for Strava down? 

### ISSUE THREAD

**Issue by snguyen268** [SauceLLC/sauce4strava#136]
Hi,

I noticed for the past 2 days, Sauce for Strava does not show on my strava activity anymore. When I click on peak performance or fitness page, I only saw a blank page. Is the extension down?

Thanks so much,
Son

**Comment by mayfield** [comment]
Hi @snguyen268 it should be working, can you hit F12 and report back with any messages you see in the console tab?

**Comment by snguyen268** [comment]
![Screen Shot 2022-11-10 at 6 00 18 PM](https://user-images.githubusercontent.com/42554578/201223939-90946cad-d039-4c29-b4eb-7729c6267c6d.png)

Here is what I got. Thanks so much for the quick response!

**Comment by snguyen268** [comment]
The above one was when I got the Peak performance page on sauce for strava. This one below is when I am on my activity dashboard
![Screen Shot 2022-11-10 at 6 03 47 PM](https://user-images.githubusercontent.com/42554578/201224485-2721322c-2d04-4e9b-b174-3e20b240fe38.png)

**Comment by mayfield** [comment]
First thing I'm noticing is another extension is changing some global constructs. Can you try disabling some of the other extensions temporarily?

**Comment by snguyen268** [comment]
I see. I just tried to disabled and restarted Chrome and it seems to have fixed it. Apologies for not trying this before posting. Thanks so much for your help!

**Comment by mayfield** [comment]
No worries, glad you're back up!
