### ISSUE TITLE
"Est Power" analysis chart in dark mode is barely visible.

### ISSUE THREAD

**Issue by atoponce** [SauceLLC/sauce4strava#141]
When using the default Strava light theme, the estimated power chart is a dark gray color:

![strava-default](https://user-images.githubusercontent.com/699572/211923889-f188e241-97fb-42dd-982b-5d53da7cf6cd.png)

However, when using the "Dark Mode" from the extension, the chart is barely visible:

![strava-dark](https://user-images.githubusercontent.com/699572/211923885-1fa6b7a4-afbd-4df5-b4e6-24f16d27e762.png)

Perhaps it could be inverted to a light gray to contrast better with the dark background?

**Comment by mayfield** [comment]
Good call, thanks for submitting this.
