### ISSUE TITLE
Power missing in stacked chart when using a foot pod

### ISSUE THREAD

**Issue by atoponce** [SauceLLC/sauce4strava#143]
When running without a foot pod or watch that records running power during a run, Sauce provides an estimated power in the analysis stacked chart ([activity here](https://www.strava.com/activities/8403462912/analysis)):

![image](https://user-images.githubusercontent.com/699572/213554799-7f0d682d-58de-4d87-aa2c-4815ebf504e2.png)

However, when running with a foot pod, such as Stryd, the power chart is missing ([activity here](https://www.strava.com/activities/8418508899/analysis)):

![image](https://user-images.githubusercontent.com/699572/213554932-5f743e96-2907-493c-83a6-22bf3b996133.png)

**Comment by mayfield** [comment]
Thanks @atoponce real running power in Strava is pretty new, so I was only looking for estimated power when I modified this page to show power (or anything for runs actually).

I didn't realize Stryd data was also being sent as real power now.  Can you tell me more about your setup, i.e. garmin and garmin-apps, etc?  I used a stryd for testing and calibration when implementing the estimated running watts but at the time Garmin stripped out the watt stream from the data stream so I could only see it on Garmin Connect.

**Comment by atoponce** [comment]
I'm running with a 2nd gen Stryd paired to my Suunto 9 Baro. My watch syncs with the Suunto mobile app which then sends the activity to Strava. Strava does have the power data. It's available in the FIT file and viewable in the mobile app (just not the web interface which is obnoxious):

![Screenshot_20230119-141115.png](https://user-images.githubusercontent.com/699572/213560251-08a47dc0-48b6-4dc8-85ef-828f9f570af4.png)

**Comment by mayfield** [comment]
Okay interesting.  I bet Garmin with Stryd is still stripping it then.  Still a valid but, but thanks for the info.

**Comment by mayfield** [comment]
Fixed in f5ff53e7625b7688603a40a5b2d198b669ba1471

**Comment by atoponce** [comment]
Schweet! Thanks!
