### ISSUE TITLE
i18n: use language set on strava website instead of browser language

### ISSUE THREAD

**Issue by tadwohlrapp** [SauceLLC/sauce4strava#148]
Currently the extension uses the language set in the browser (`browser.i18n.detectLanguage`).

This creates issues when the browser language differs from the language in which strava.com is used.
In my case, my browser language is set to German, but I prefer to use Strava in English, so currently Strava's regular content is shown in English, while all additions provided by sauce4strava are in German.

How about querying `document.documentElement.lang` instead?

**Comment by mayfield** [comment]
Unfortunately the locale system is a bit of a black box.  The main call used for getting locale based messages is `i18n.getMessage()` and it doesn't support alternate locales.  From the context of the running extension I can't even see the translation files I bundle with the extension; they are only accessible through the `i18n` calls.

`detectLanguage` and `getUILanguage` just tell the extension what local a string is and what the browser is configured for respectively.  It's a pretty glaring hole in the extension system TBH.  I would love to let users control the language used as well as use a more appropriate source for the locale like in the method you suggested.

It's not the best solution in the world but this is how I test locales on my rig by creating custom launchers for chrome with the arguments to force it to a specific locale: https://developer.chrome.com/docs/extensions/reference/i18n/#how-to-set-browsers-locale
