### ISSUE TITLE
"kudo" everthing not working?

### ISSUE THREAD

**Issue by ferednun** [SauceLLC/sauce4strava#149]
just in the last couple days "kudo everything" isn't working.

i'm not sure if it's just me... i've cleared everything in firefox, reset everything, logged out and back in, etc.

any idea why?

here's a screen cap:

https://user-images.githubusercontent.com/125715389/219829928-9b6250e0-dc08-42ee-804b-6cf17f4e09ca.mov

**Comment by mayfield** [comment]
It's not just you, but the upstream change to that page hasn't gotten to me yet (Strava takes about a week to fully roll out changes).  I'll revisit as soon as mine is affected and see what needs to be changed.

**Comment by WightBoi** [comment]
Mine stopped working on both FireFox and Chrome... definitely not just you

**Comment by andrewbulloch** [comment]
Broken in Safari on Mac Ventura 13.2.1 (22D68) as well

**Comment by piaseq** [comment]
Same here, Opera, Chrome. Latest releases.

**Comment by mayfield** [comment]
Frustratingly I can't replicate this on my test accounts even with geo fuzzing.  This is either the slowest roll-out ever or some A/B testing.  So I'm requesting a little help from anyone willing to triage with me...

I need to see the full contents of the HTML body tag after the dashboard is fully rendered.  On __Google Chrome__ please, go to the normal dashboard page, make sure it's a clean load and then perform the following steps:
 1. Hit F12 to open Dev tools
 2. Go to the Elements tab (top bar)
 3. Find the `body` tag near the top of the tree.
 4. **Right click** this `body` tag and select **Copy** -> **Copy outerHTML**
 5. Open a plain text editor (not a word processor or code editor).  On windows, wordpad or notepad will probably work, on mac TextEdit should probably work.
 6. Use the paste keyboard shortcut for your platform; `Ctrl+V` (win) or `Command+V` (mac)
 7. Save the results of this new file to `foo.txt`.  Make sure the program you paste into doesn't try to convert it to HTML or anything fancy, I just want the raw text.
 8. Email **(please don't attach here, I don't want any of your private info revealed)** this file **as an attachment (important)** to **support@sauce.llc** .  If your email client wants to inline the contents, try renaming it to foo.raw or something obtuse so it doesn't recognize the file format and just includes the raw data.

**Comment by ferednun** [comment]
@mayfield i just sent foo.txt to you, from firefox 110.0 running on mac os ventura 13.1

**Comment by lcarcamo1526** [comment]
@mayfield I did send a foo.txt from Chromium in Arch linux

**Comment by andrewbulloch** [comment]
Send an email to support@sauce.llc with foo.txt as requested 👍

**Comment by mayfield** [comment]
FYI: I've prototyped a fix based on the data you guys sent.  I also decided it was time to do a more powerful filter system.  This is what I have so far...
![image](https://user-images.githubusercontent.com/139316/221051647-0f05bd68-893e-4c85-aa71-637cb262ef22.png)

Click on each of the terms in the footer of the table and select from a range of options then add the filter, which can do a few different actions like hide, hide images, hide all media or "highlight".

**Comment by ferednun** [comment]
> FYI: I've prototyped a fix based on the data you guys sent. I also decided it was time to do a more powerful filter system. This is what I have so far... ![image](https://user-images.githubusercontent.com/139316/221051647-0f05bd68-893e-4c85-aa71-637cb262ef22.png)
> 
> Click on each of the terms in the footer of the table and select from a range of options then add the filter, which can do a few different actions like hide, hide images, hide all media or "highlight".

the new filter system is pretty snazzy... can't wait to try it. is there any way to "add" or "unhide" others who were part of the activity who i am not following? it's kind of like the phone "shake" feature on strava when we give kudos to everyone on an activity, whether we're following them or not. sorry if this is on a tangent...

just out of curiosity... what actually was "broken" that you fixed?

**Comment by mayfield** [comment]
> > FYI: I've prototyped a fix based on the data you guys sent. I also decided it was time to do a more powerful filter system. This is what I have so far... ![image](https://user-images.githubusercontent.com/139316/221051647-0f05bd68-893e-4c85-aa71-637cb262ef22.png)
> > Click on each of the terms in the footer of the table and select from a range of options then add the filter, which can do a few different actions like hide, hide images, hide all media or "highlight".
> 
> the new filter system is pretty snazzy... can't wait to try it. is there any way to "add" or "unhide" others who were part of the activity who i am not following? it's kind of like the phone "shake" feature on strava when we give kudos to everyone on an activity, whether we're following them or not. sorry if this is on a tangent...
> 
> just out of curiosity... what actually was "broken" that you fixed?

No I can't manifest the non-followees from group rides.  The data must be in the page in the first place.  So it's almost all exclusionary.

The change is just some meaningless React.js refactoring that causes the generated DOM to be different..
![image](https://user-images.githubusercontent.com/139316/221057901-9cd166a3-69db-4ad7-b97a-a33703e76ec7.png)

**Comment by andrewbulloch** [comment]
Any idea when we can expect to see the fix for the "Kudo everything" issue making it's way into the Apple App Store version of the Safari extension ?

Thanks

**Comment by mayfield** [comment]
FYI: Submitted builds to Firefox and Chrome store.   Firefox already approved it, so look for `v8.2.0` to get the fixes.

**Comment by andrewbulloch** [comment]
Thanks for the hard worked resolving this quickly 👍 Confirmed it's working for me in Chrome and Firefox 8.2.0 @mayfield, how long before we can see the Safari Extension updated to 8.2.0 (it's my main browser of choice on the Mac 😋 )

**Comment by ferednun** [comment]
Many thanks. Tried it today. Everything looks like it's working again.
Cheers.

    On Sunday, February 26, 2023 at 05:53:45 PM GMT+8, Justin Mayfield ***@***.***> wrote:  
 
 


FYI: Submitted builds to Firefox and Chrome store. Firefox already approved it, so look for v8.2.0 to get the fixes.

**Comment by andrewbulloch** [comment]
Seems borked again today ? Using Sauce 8.2.0 on Chrome or Firefox - getting the "Everything Kudo'd" again.  Sent email again to support@sauce.llc account.

**Comment by mayfield** [comment]
Yup, they changed the layout **yet again**.  Fortunately the roll-out must have been immediate and I can see it.  Fix is in place and rolling out release of v8.2.1.  Hopefully it sticks for more than 24 hours. :frowning_face:

**Comment by ferednun** [comment]
lol… ok. i was wondering what happened. i was going to wait a day or so and see before saying anything. On Mar 3, 2023, at 8:25 AM, Justin Mayfield ***@***.***> wrote:﻿
Yup, they changed the layout yet again.  Fortunately the roll-out must have been immediate and I can see it.  Fix is in place and rolling out release of v8.2.1.  Hopefully it sticks for more than 24 hours. ☹️

**Comment by itsonlybarney** [comment]
I just sent an email to support using the above steps. Seems Strava borked for me. 

Firefox: 115.0.3 (64-bit)
Sauce for Strava: 8.2.3 (344a48c610)

**Comment by jokuha** [comment]
Strava seems to have changed the layout again... at least, I do have the same problem again for some days already.
