### ISSUE TITLE
Exported TCX no longer compatible with Golden Cheetah

### ISSUE THREAD

**Issue by CarlosWilkes** [SauceLLC/sauce4strava#15]
My rides automatically upload to Strava, and I use the 'Export TCX' feature from Sauce so I can then import them into Golden Cheetah. Prior to version 7.0.0 this seemed to work fine.

However, it seems like something about the exported TCX file makes it no longer compatible with Golden Cheetah. Upon import it says the ride has a duration of 1 second and a distance of 0. The TCX filesize looks right, and the TCX file appears to open fine in GPXSee, so perhaps this is an issue with GC, though it used to work fine.

If I go to the Analysis tab the TCX from there also doesn't work. The GPX export does work though, but it seems to lose cadence data.

Slightly off topic, but both the TCX and GPX files exported from Sauce lack lap data. I don't know about GPX, but I know TCX is capable of storing this.

**Comment by mayfield** [comment]
Well that is a bummer.   I actually fixed lap handling for TCX files when
imported into Garmin Connect.   However I'd rather have GC working properly
so I'll probably revert that. I'll send you a build as soon as I'm done so
you don't have to wait for the store to update (sometimes takes days for
them to reveiew).

Thanks for reporting it.
JM

**Comment by mayfield** [comment]
Hi @CarlosWilkes, fixed the issues.  Attached is a build you can try if you don't want to wait for the next release.  But as soon as I can I'll publish this fix.  Thanks!  Also this fix has laps working properly in GC too.  So all good.  I just messed up the Lap start time attribute and Garmin Connect didn't care, but GC does.
[sauce-chromium-8a25837.zip](https://github.com/SauceLLC/sauce4strava/files/5615004/sauce-chromium-8a25837.zip)

**Comment by CarlosWilkes** [comment]
@mayfield Thanks, this new build fixes the TCX export with GC!

Laps still seem to be missing though. Today I did a ride with 5 laps (as shown in Strava). The exported TCX only has one <lap></lap> though, and I see no laps when imported into GC.

**Comment by mayfield** [comment]
Can you send me the URL for the activity?

**Comment by mayfield** [comment]
I should add, that laps are not exported when using the TCX export from the analysis box.  I'd have to do more work to figure out all the overlapping areas since you can make custom selections in that context.  Not impossible, but currently I'm only doing lap exports from the full activity export (via the left nav menu).

**Comment by CarlosWilkes** [comment]
Yeah I'm talking about the entire activity Export TCX feature. You can find my activity here: https://www.strava.com/activities/4410635959

**Comment by mayfield** [comment]
@CarlosWilkes I think I see what's happening there and did another patch.  The lap efforts don't load in every page context.  So I'm forcing them to fetch from the network.  Also I fixed another issue when trying to export someone else's activities with privacy zones.   New build attached..

[sauce-chromium-bd81c7d.zip](https://github.com/SauceLLC/sauce4strava/files/5615384/sauce-chromium-bd81c7d.zip)

**Comment by CarlosWilkes** [comment]
Looks like it all works now, great job!

**Comment by mayfield** [comment]
Excellent.  Thanks for the feedback and testing.
