### ISSUE TITLE
Peer activity sync needs to handle new upstream changes

### ISSUE THREAD

**Issue by mayfield** [SauceLLC/sauce4strava#151]
Strava changed the nesting of the embedded JSON used to describe activity feeds, thus breaking activity sync for peers.

The change is slowly rolling out, or is in a A/B test with a fixed quota as I can't see the change myself directly, but I have countless users experiencing this.

Related to #149

**Comment by Paulshoe60** [comment]
Is this why Strava for Sauce in Safari stopped showing TSS, Intensity Factor, number of beers, and seemingly all other integrated Sauce functionality on Strava as of today? Or, is my issue different.

**Comment by mayfield** [comment]
> Is this why Strava for Sauce in Safari stopped showing TSS, Intensity Factor, number of beers, and seemingly all other integrated Sauce functionality on Strava as of today? Or, is my issue different.

Not that I'm aware of.  I've heard a couple other users saying the same thing but I also can't reproduce it.  If you have dev console logs with errors, could you file a new issue @Paulshoe60 ?
