### ISSUE TITLE
Kudo All stopped working

### ISSUE THREAD

**Issue by dusankoutnik** [SauceLLC/sauce4strava#152]
Clicking the button "Kudo All" will change the button description to "Everything Kudoed", but nothing else will happen.
Win 11, last Chrome. I think it hasn't worked since the last Chrome update.

**Comment by blhuynh** [comment]
Not working for me either on MacOS on Chrome or Safari.

**Comment by judgeg** [comment]
Firefox on Windows 11 also not working. Maybe Strava changed something?

**Comment by tcoursey** [comment]
Same here.  Brave.  Uninstalled and re-installed Sauce.  Had a windows update, ran that, rebooted, still no go.  I bet Strava did something!

**Comment by judgeg** [comment]
Firefox extension just updated to v 8.2.0 and all is working now :-)

**Comment by tcoursey** [comment]
> Firefox extension just updated to v 8.2.0 and all is working now :-)

Good to know.  Brave is still on 8.1.3.  I'm sure it will come out soon enough.  Thanks!

**Comment by dusankoutnik** [comment]
Today updated to 8.2.0, working. Thanks!

**Comment by atoponce** [comment]
It stopped working again. Reopen the issue?

**Comment by dusankoutnik** [comment]
Yes. :-(

**Comment by calzone123** [comment]
Looks like with 8.2.1. it's working again :)

**Comment by dashie** [comment]
v8.2.3 on Chrome/Mac and it does not work

**Comment by dominikrappaport** [comment]
Not working for me too with extension version 8.2.3 on Mac (13.5), Chrome version 115.0.5790.114.

**Comment by RealGrep** [comment]
Broke on Linux with Firefox as well. Reckon Strava changed something again.

**Comment by Coachbur** [comment]
Mac OS and iPhone IOS not working.  Almost a week.  Sent an email and got no response.

**Comment by mayfield** [comment]
Fixed via #167

**Comment by Coachbur** [comment]
Does this mean it’s fixed?  Net working here. Sent from my iPhoneOn Aug 7, 2023, at 6:07 PM, Justin Mayfield ***@***.***> wrote:﻿
Closed #152 as completed.

**Comment by Coachbur** [comment]
And Safari?Sent from my iPhoneOn Aug 8, 2023, at 4:29 AM, Dominik Rappaport ***@***.***> wrote:﻿
@Coachbur So far, just the source code was patched but the plugin in Chrome's repo has not yet been updated.
