### ISSUE TITLE
Where is export to GPX?

### ISSUE THREAD

**Issue by jeffrey-friedl** [SauceLLC/sauce4strava#154]
Hi There,
I see the export to FIT and TCX, but no export to GPX.... am I missing something?
(Strava's standard GPX export option is there, but that doesn't include trackpoint times)

Thanks!

**Comment by mayfield** [comment]
I disable the GPX export if it's already an export option from Strava.

**Comment by jeffrey-friedl** [comment]
Would you consider including the your GPX export regardless? The built-in Strava GPX-export does not include times or watts or heartrate, etc.  Thanks!

**Comment by kshji** [comment]
All views show Sauce GPX ... but yes it has removed.
