### ISSUE TITLE
Test and add support for Orion browser

### ISSUE THREAD

**Issue by jpweytjens** [SauceLLC/sauce4strava#155]
The [Orion browser](https://browser.kagi.com) is a new browser that's build with the WebKit with support for both Chrome and Firefox extensions. It's currently in beta, but most Chrome and Firefox WebExtensions work out of the box.

This is currently not the case for Sauce4Strava. The settings panel is available, but the addon is not visible on the Strava website. Orion allows you to change the UserAgent per site. Changing it to `Chrome` shows the Sauce Performance menu in the Strava Training dropdown, but none of the pages are available. 

![CleanShot 2023-03-13 at 10 31 31](https://user-images.githubusercontent.com/34494702/224661739-f69053af-c497-45b4-ba74-9504e62c440e.png)

Orion states on their [FAQ](https://browser.kagi.com/faq.html) that only ~70% of the WebExtensions API is supported as of now. Despite this fact, it seems that Sauce4Strava currently has some internal config that assumes the browser is Chrome?

Would it be possible to test Sauce4Strava in Orion as well? I'll happily provide further festing and logs to help with this endeavour.

**Comment by mayfield** [comment]
Hi @jpweytjens, thanks for making me aware of a new browser with extension support.

Looks like the issue is a bug in Orion.  I created an issue so they can hopefully fix it.

https://orionfeedback.org/d/4730-postmessage-with-transfer-object-is-broken

**Comment by mayfield** [comment]
The bug affecting Orion support is actually a Safari/WebKit bug.

https://bugs.webkit.org/show_bug.cgi?id=254777

I figured out a workaround and published it to the Firefox store (which is the store that should be used for an Orion install).

Basic functionality works but Sauce Performance is hindered by some of the same issues that affect Safari so I don't recommend trying it.

Install Sauce from here:
https://addons.mozilla.org/en-US/firefox/addon/sauce4strava/

**Comment by jpweytjens** [comment]
Thanks for all this work @mayfield .

**Comment by mayfield** [comment]
@jpweytjens Just wanted to let you know the webkit team just landed a fix for this bug.  So you helped make Safari and Orion a little bit better by submitting this issue.

**Comment by jpweytjens** [comment]
Thanks for the update! With this fix, does it matter whether Orion users install the Firefox or the Chrome version?

**Comment by mayfield** [comment]
> Thanks for the update! With this fix, does it matter whether Orion users install the Firefox or the Chrome version?

Yeah, you'll likely always want to use the Firefox based ext.  The Chrome one uses some APIs that are unique to it.  Even the native Safari build is essentially the same as the Firefox one.
