### ISSUE TITLE
Running Power is skewing TSS

### ISSUE THREAD

**Issue by somatech-uk** [SauceLLC/sauce4strava#157]
I have been using the app for a while now with power data coming from cycling and running data just being pace/HR with no issues. I recently purchased the Garmin Forerunner 965 which has running power data attached to the run.

This looks to be causing an issue with TSS and IF - I did a 40 min base run at a slower pace, the TSS shows as 31 for tTSS but 168 for TSS Power. IF is also showing at 157%

![image](https://user-images.githubusercontent.com/57303688/226171379-a8a62ddb-740e-42e5-94ea-9543c15094ae.png)

Is there a way that I can disable power for running but keep it for cycling within the app?

**Comment by mayfield** [comment]
Yeah, I need to add an option to disable run power now that Garmin is basically ruining it! :smile:
