### ISSUE TITLE
Can not get the FTP set by others

### ISSUE THREAD

**Issue by tcxuzuo** [SauceLLC/sauce4strava#159]
![微信截图_20230523084503](https://github.com/SauceLLC/sauce4strava/assets/30023173/b0447541-f21e-4bc1-9c35-57b36a3288ed)

**Comment by mayfield** [comment]
Looks like it's not in the `PowerController` instance anymore.  Strangely for self-activities it IS on the `Activity` instance which was previously deprecated.  Not sure what they are up to.  Maybe it's an upstream regression.  I'm going to wait at least a week before diving back into this.  Sometimes they make mistakes and roll back.  I find it hard to believe that this was related to a feature.

**Comment by mayfield** [comment]
Patched up FTP detection as best as I can see how to with e83f7a084c2141afee1bb0f5466ce56ed916f14b
