### ISSUE TITLE
Feature Request: Include Drivetrain Loss in Performance Predictor

### ISSUE THREAD

**Issue by kerednoslo** [SauceLLC/sauce4strava#160]
Request inclusion of drivetrain loss percentage (nominally 2%). I found that it provides more consistent agreement with measured times and power on climbs if I decrease the measured power by about 2%. Would be nice to have this feature built in.

**Comment by mayfield** [comment]
I'm currently doing 3.5% for drivetrain loss. Is it possible some of the other knobs are not quite right for your setup?  Like CdA or rolling resistance?  Also the gear weight should include your clothes, water, bike, tools, i.e. the sum of all non body weight items.  Sometimes folks assume it's just bike weight but I'm not including any other constants for weight.

Probably not relevant but is your air exceptionally humid?  My air density function doesn't take into account humidity, just elevation, so although unlikely I'm sort of curious if your env is such that I should be taking it into account.
