### ISSUE TITLE
Crop ride interface is broken when Sauce is enabled

### ISSUE THREAD

**Issue by willvousden** [SauceLLC/sauce4strava#161]
The "crop ride" interface appears to be broken when Sauce is enabled.

The map and slider control are squashed horizontally and appear below and to the left of the text and buttons, with a large empty space occupying the entire right side of the page. The elevation profile is squashed even more than the map and barely usable. Disabling Sauce restores the page to how it should look.

### Steps to reproduce

1. Install/enable Sauce
2. Go to any ride, click the three dots, and go to `Crop`
3. The page looks broken

### Expected behaviour

It should look like this:

<img width="1458" alt="Screenshot 2023-06-24 at 13 46 58" src="https://github.com/SauceLLC/sauce4strava/assets/152388/b4949805-8f99-4cbf-84f5-55fea6d17edc">

### Observed behaviour

It looks like this:

<img width="1461" alt="Screenshot 2023-06-24 at 13 42 50" src="https://github.com/SauceLLC/sauce4strava/assets/152388/17dd067d-1174-4aef-a61a-b2a061056c78">

And scrolling down a bit:

<img width="1458" alt="Screenshot 2023-06-24 at 13 43 00" src="https://github.com/SauceLLC/sauce4strava/assets/152388/e7b74449-b479-4311-9bb4-07fda68739b0">

### Extension/browser versions

**Sauce:** 8.2.3
**Browser:** Brave, Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (arm64)

**Comment by mayfield** [comment]
Fixed in 8.4.3+
