### ISSUE TITLE
No access to Sauce performance metrics

### ISSUE THREAD

**Issue by nymi84** [SauceLLC/sauce4strava#163]
Hi!

I have become a Patron member (2$/month) but I can still not access the strava performance metrics in the training menu. What is wrong with my account - do I have to link my Patron membership with the Sauce plugin?

Thanks for your help!

**Comment by mayfield** [comment]
Hi @nymi84 pinged you on discord, going to close this out under the assumption we can get you up and running over there.

**Comment by nymi84** [comment]
I have not received anything on discord (or I'm overlooking it). Is there a discord server for the Sauce Plugin?

**Comment by mayfield** [comment]
Oh funny, you have a very similar username to a user on discord having similar issues so I assumed it was you!

Can you email me a screenshot with where you're stuck at to support@sauce.llc ?

**Comment by mayfield** [comment]
Oh and yes, there is a pretty active discord server.   Look for a link on the Patreon posts for details.
