### ISSUE TITLE
Kudo All Broken in Safari and Firefox on macOS

### ISSUE THREAD

**Issue by andrewbulloch** [SauceLLC/sauce4strava#165]
Kudo All seems to be goofed.  Running Sauce for Strava 8.2.2 on Safari on Mac OS 13.4.1 (c) (22F770820d). "KudoAll" doesn't seem to do anything at all in the latest version of Strava - it simply says "Everything Kudod" instantly but doesn't actually do anything.

**Comment by mayfield** [comment]
Closing in favor of #152

**Comment by andrewbulloch** [comment]
Hi Justin, I know I reported this back in March and you fixed it but it's definitely broken again for sure, doesn't work across Safari, Firefox or Chrome on Mac OS since 28th July 👍
