### ISSUE TITLE
Kudo all not working (again)

### ISSUE THREAD

**Issue by jokuha** [SauceLLC/sauce4strava#166]
As I cannot open the other issue, here's a duplicate (sorry, please close as "duplicate" once the other is re-opened)

Strava seems to have changed the layout again... at least, I do have the same problem again for some days already.

_Originally posted by @jokuha in https://github.com/SauceLLC/sauce4strava/issues/149#issuecomment-1659692334_

**Comment by MacGyverQue** [comment]
Confirmed on my end as well

**Comment by iScrtAznMan** [comment]
looks like #152 is open again for 8.2.3 as mentioned on #165

**Comment by elicriffield** [comment]
Chrome and Brave "Kudo All" not working for me

**Comment by piaseq** [comment]
Same here

**Comment by mayfield** [comment]
Fixed via #167

**Comment by Coachbur** [comment]
Any progress made on fixing Kudo All.  Seem to be getting mixed messages.

**Comment by elicriffield** [comment]
It's working for me now, try uninstalling then reinstalling to make sure you have the latest version

**Comment by geno333** [comment]
Yes, it resumed working again with the latest fix that came along a few days ago.

Thanks!

**Comment by Coachbur** [comment]
Got it working in Chrome by turning the extension off and back on.  Uninstalled and reinstalled in Safari.  No luck.  Using Mac OS

**Comment by simonf00** [comment]
Same for me... works in Chrome/Edge but does not work in Safari.

**Comment by geno333** [comment]
Works fine in the Brave browser

**Comment by simonf00** [comment]
Indeed... It looks like it works on Firefox and all Chromium based browsers. Safari needs fix though.

**Comment by Coachbur** [comment]
Kudo all works in Chrome on Mac OS.  Does not work on anything in IOS on iPhone.
