### ISSUE TITLE
Why is the initial Predicted Performance not the same as Original Performance?

### ISSUE THREAD

**Issue by MalpaMaison** [SauceLLC/sauce4strava#17]
If the rider weight and My Gear is correctly set in Strava, why does "Bike/Gear Weight" show a different value in Performance Predictor?

When the "Bike/Gear Weight" in Performance Predictor is reset to the same value as set in Strava, why is the "Predicted Performance" so far off from the "Original Performance"?

I would have expected the baseline to be the same.

**Comment by mayfield** [comment]
Hi @MalpaMaison I don't have access to the Strava bike/gear weight settings.  Those values are embedded into the HTML of your settings page in way that's not reliably accessible.  Also it would only work for activities performed by the logged in athlete.  So I just pick a reasonable starting value and if you change it, it saves it in a preference for that athlete so you don't have to re update it each time you jump into the perf predictor for that person.

As far as being off from the original.  A lot of factors are in play but here is a short list of things to consider.

1. If the power data is from estimated watt calcs, it is likely to be inaccurate.  Strava is just guessing what you watts might be, and it's a blackbox algo, so nobody really knows what goes into it.   A real power meter is the best source for original watt performance.

2. The weight is your bike and everything else, water bottles, saddle bags, clothes, shoes, etc.  It should represent the total weight of everything that is not your body weight.

3. Getting the rolling resistence and aero dynamic drag settings right is critical.  If you're mountain biking for example, the Crr usually needs to be tuned by hand to hone in on the exact conditions of the trail in use.

4. If you're riding in a pack or have any sort of draft aid, then putting a negative wind speed in is nessisary to compensate for the aerodynamic drag decrease.  Probably something like -5 mph to -10 mph for small groups moving at 20 - 25 mph.

What I like to do is find a reliable data source for a segment, preferably with a real power meter source and then tune the aforementioned values by hand until the original perf and the predicted perf are nearly the same.  This will then give you a blueprint for what Crr, and CdA, etc to use for that segment, then from there you can tweak values like weight and power to see what will happen if you magically lose weight or gain a bunch of power.

I hope some of this helps.  If you're still having issues, feel free to send me a particular activity and/or segment that's acting funny and I can take a look myself.

**Comment by mayfield** [comment]
One more note.  The algo used by Sauce is just classical physics that's been around for ages.  Tried and true.  You can see the maths at sites like this one: https://www.gribble.org/cycling/power_v_speed.html

And in the sauce code here:
https://github.com/SauceLLC/sauce4strava/blob/37233256cbe07acd51645cea8deb73db911c5e78/src/common/lib.js#L928-L973

**Comment by MalpaMaison** [comment]
Yes, that additional info helps.  

1. I am using a power meter 
2. I am using the weight of the bike and everything else as you prescribe
3. I will attempt to figure out the CdA and Crr
4. Solo ride I don't remember the wind conditions

https://www.strava.com/activities/7404732/segments/138683451

Do you have an ETA your Firefox plugin?

Do you have a one time sponsor option instead of monthly?

**Comment by mayfield** [comment]
Firefox is already out there..

https://addons.mozilla.org/en-US/android/addon/sauce4strava/

I added Safari support too, but I'm not willing to pay Apple tax, so it's just a developer signed download on the website: https://saucellc.io (top right corner or bottom right if you aren't currently using safari to view the site).

No non monthly patreon at present, sorry.  

I'll have a look at activity you posted in the next day or two, thank you!

**Comment by Filliny** [comment]
Perfomance predictor dont count on pauses - so i see the initial average speed is lower than original
