### ISSUE TITLE
KudoAll button vanished

### ISSUE THREAD

**Issue by dominikrappaport** [SauceLLC/sauce4strava#171]
![2023-09-14_08-43-21](https://github.com/SauceLLC/sauce4strava/assets/32907331/f0a0caa7-2f98-49bb-868c-31b413dc5c09)
Hi,

Today after a Google chrome update (to Version 116.0.5845.187 (Official Build) (arm64)) the Kudo All button vanished from Strava's activity feed page. I verified that the Sauce plugin (8.2.5) is still working (it's available in the menus as well as when I open an activity). Needless to say, a refresh didn't resolve the issue.

I can't tell for sure if the Chrome update is related to the issue or if it was just coincidence. Obviously I can't rule out local issues on my Mac but considering that everything else with Sauce is working fine, I suspect either a Chrome or Strava update being responsible. Happy to be proven wrong, though.

**Comment by mayfield** [comment]
Hi @dominikrappaport can you attach a screenshot?  Strava is rolling out more updates to the dashboard and I wonder if you're on the tail end of the rollout because 8.2.5 is updated to work with the latest changes (that I've seen).

**Comment by adrenalinenz** [comment]
Also missing for me, I'm using Firefox 117.0.1 and Sauce plugin version 8.2.5

![image](https://github.com/SauceLLC/sauce4strava/assets/10415305/010171b6-5ba7-4666-b8fc-8db6a2861c3f)

**Comment by mayfield** [comment]
> Also missing for me, I'm using Firefox 117.0.1 and Sauce plugin version 8.2.5
> 
> ![image](https://user-images.githubusercontent.com/10415305/267803520-010171b6-5ba7-4666-b8fc-8db6a2861c3f.png)

Looks like your're still getting the old dashboard.  The new one has the "Following" dropdown in a button.  In a few days you'll probably have the updated site and 8.2.5 will work again.

**Comment by dominikrappaport** [comment]
> Hi @dominikrappaport can you attach a screenshot? Strava is rolling out more updates to the dashboard and I wonder if you're on the tail end of the rollout because 8.2.5 is updated to work with the latest changes (that I've seen).

Hi,

I've just attached a screenshot to my original post. Indeed, the Strava front page looks as usual which suggests I'm not on their new design. Following your suggestion, I'll wait until they migrate me ot the new one which hopefully brings back the button.

**Comment by dashie** [comment]
I'm without the button too!

<img width="1238" alt="Screenshot 2023-09-16 alle 18 49 43" src="https://github.com/SauceLLC/sauce4strava/assets/913231/b0752ec7-e0b7-4449-82be-5c702237e999">

**Comment by piaseq** [comment]
Same here. Kudo all button and some other Sauce menus are gone...

**Comment by dominikrappaport** [comment]
As predicted, the button appeared again. I'm closing the issue.
