### ISSUE TITLE
TSS value shown on Fitness Tracking page, does not match TSS shown on activity

### ISSUE THREAD

**Issue by simonwross** [SauceLLC/sauce4strava#172]
The TSS value calculated by S4S and shown on the Fitness Tracking and the detailed activity page for the same activity are very different. See screen shots. 

![Activity screenshot](https://github.com/SauceLLC/sauce4strava/assets/15135300/a0afaafa-1ac6-49df-b24f-09a533b1008b)
![Fitness Tracking Screenshot](https://github.com/SauceLLC/sauce4strava/assets/15135300/e57f2030-4dbd-474f-81ea-b7212a0cafc8)

**Comment by mayfield** [comment]
Hi @simonwross the blue color on your FTP for that activity pic suggests that this athlete isn't syncing (currently at least).  When sync is enabled the FTP (which affects TSS) will be used directly from the Sauce managed values (the table of date based FTPs in the Sync Panel).  Can you check the sync state of this athlete and check what the FTP settings say there too?

**Comment by simonwross** [comment]
Hi @mayfield all the activities show sync'd. That 240W in blue in the original activity is the FTP I have stored in Strava. See attached screenshot of sync status, you can see I haven't manually entered FTP - is there somewhere I should be looking on the fitness tracking? Are they pulling the FTP from the same source? 
![image](https://github.com/SauceLLC/sauce4strava/assets/15135300/3a681ecf-e59f-4b06-b490-71095e323e2f)

**Comment by mayfield** [comment]
@simonwross looks like the FTP History table is empty.  If you add an FTP entry to that table (click the + button) all the TSS values will update and trigger updates to fitness values too.

**Comment by mayfield** [comment]
Regarding source of FTP value: When sync is enabled Sauce Performance will use the FTP values from the athlete's Sync Panel (only) which is why your TSS values aren't matching up.
