### ISSUE TITLE
Sauce for Strava not showing other people's weight anymore

### ISSUE THREAD

**Issue by JoeriN55** [SauceLLC/sauce4strava#173]
Hi!

For a few months now, I can't see other people's weights anymore so also no W/kg estimates for certain efforts/KOM attempts. I've tried to re-install the plug-in multiple times but that doesn't seem to solve the issue.. Any idea why or what I can try to do about it?

Thanks!

**Comment by JoeriN55** [comment]
I just checked and the issue is there in both Chrome and Edge.

**Comment by philcbu** [comment]
This might be a Strava issue. I've noticed another extension can no longer show the weight and has everyone at 70kg

**Comment by mayfield** [comment]
Did a full investigation and weight is gone from 99% of non-self activities now.

**Comment by philcbu** [comment]
What does that mean? Unfixable?

**Comment by mayfield** [comment]
> What does that mean? Unfixable?

Yeah.
