### ISSUE TITLE
Sauce extension is not working in strava and iOS and chrome since yesterday

### ISSUE THREAD

**Issue by ObadahA** [SauceLLC/sauce4strava#174]

**Comment by mayfield** [comment]
Hi @ObadahA can you provide some more context?  Photos, logs, versions, etc.

**Comment by ObadahA** [comment]
![Screenshot 2023-11-07 at 9 36 22 AM](https://github.com/SauceLLC/sauce4strava/assets/150081203/00066b7b-ebfb-4239-a65c-9860dfbe8e49)
I don't see the datails of sauce plug in as I used to.

**Comment by mayfield** [comment]
Thanks for that @ObadahA Can you checkout the contents (and post here if relevant) of Safari -> Preferences -> Extensions -> Sauce for Strava.

And if that is enabled as expected can you check that contents of "Edit Websites..." under the Sauce for Strava Permissions section.  It should say something to the effect of "strava.com: [allow]"

Lastly if all those things look good (enabled, etc).  Can you enabled Safari Developer options and then right click on the page (any strava activity is good) and see what the "Console" tab of the developer tools has in it?

**Comment by ObadahA** [comment]
Thank you so much! It’s working right now as before
