### ISSUE TITLE
On several FIT file exports times are totally off

### ISSUE THREAD

**Issue by archaeop** [SauceLLC/sauce4strava#177]
On several FIT file exports the times are off by days and hours. I could not find a clear indication, which activities / recording devices are affected, what I can say: I could only see the effect at activities recorded by a clock, eiteher Garmin or Polar. But a friend of mine using a Garmin 245 music has the effect, while my own activities recorded on a Garmin 245 music too are fine.

**Comment by archaeop** [comment]
Here is an example, which should be generally available: 
https://www.strava.com/activities/10252700067
By re-importing the exported FIT file you can easily see the difference

**Comment by archaeop** [comment]
After several additional tests I see the following logic:
-the problem only occurs on runs, not on rides (sounds strange, but I could recreate this at sveral runs+rides of a friend, who records both on a Garmin forerunner 245 music)
- if the problem occurs, the date shown is always the current date, the time seems to be always in the future (from the time of export)
- the problem does not occur on my own runs, but seems to be there at all(?) runs of connected people
- the problem is also included in TCX file exports
- the problem was there with both Polar and different Garmin watches

**Comment by archaeop** [comment]
Thank you very much for diving so deep into this problem.
For me, it would be sufficient, if the time would be in GMT, the most annoying thing currently is, that the time is offset by something variable. Even the duration seems always a bit off (a few minutes / hour)

**Comment by mayfield** [comment]
See #214
