### ISSUE TITLE
Dark Mode not/partially working on some pages

### ISSUE THREAD

**Issue by eprowe** [SauceLLC/sauce4strava#18]
Dark mode doesn't appear to be working 100%.  Not sure about other themes.  Here are the few I've found.  Using Firefox 86 and Sauce v7.0.4

- Local legend status of a segment.  Sample URL: https://www.strava.com/segments/19032443/local-legend
- Training > Training log.  Sample URL: https://www.strava.com/athletes/13340377/training/log
- Dashboard > Heatmaps.  Sample URL: https://www.strava.com/athlete/heatmaps?v2=true

**Comment by mayfield** [comment]
Sadly, there is nothing to be done for those pages.  Strava has embraced a React and webpack configuration that is completely unthemeable.  At first I was able to support them with some horrific CSS selectors but they switched settings in recent months and the HTML produced by them is now utterly garbage.  Hopefully they cease the rewrites of other pages with this new system cause it's a show stopper for browser extensions.

So much for the extensible web. :(

**Comment by GoustiFruit** [comment]
I guess that there was a new update to Strava (or maybe to Sauce ?), and the theming is now wrong on every page now. The only way to get working pages, is to disable Sauce. If I enable the Dark, Native, or System options, the result is the same (mostly dark background, with white "boxes").
Could you please add an option to fully disable the theming from Sauce ? Or even fully remove it ?
So that, if we want, we can use other external extensions to manage Strava's theming.

**Comment by mayfield** [comment]
@GoustiFruit I'm not able to reproduce this, but that doesn't mean it's not real.  It could be a slow rollout of some changes that aren't in my region yet.  Can you send me some screencaps and check that any other Strava related extensions aren't at fault by disabling them temporarily?

Also if you're inclined I'd like to see some of the contents of the dev tools, specifically some of the `Elements` tab on one of the affected pages.

Thank you!

**Comment by GoustiFruit** [comment]
Hi,
Here are a few screenshots of what Strava looks like in my browser, with and without Sauce. Context: Vivaldi browser on Linux (ArcoLinux/KDE Plasma).
I have no other extension related to Strava (I also attach  a screenshot of the list of the extensions installed in my browser).
![2021-07-28 19 16 04 www strava com d74b06a5890a](https://user-images.githubusercontent.com/52235969/127370632-c79e22cb-3af0-4d78-9cf9-0951faa129f3.png)
![2021-07-28 19 14 21 www strava com 28eaaf681e95](https://user-images.githubusercontent.com/52235969/127370825-16dc89bc-7f2b-4c76-b5cd-5d056e7e3682.png)
![Screenshot_20210728_192028](https://user-images.githubusercontent.com/52235969/127370691-6d9b1be4-5616-461c-9751-61689b83be5f.png)
![2021-07-28 19 24 31 extensions d225bba2e2a9](https://user-images.githubusercontent.com/52235969/127370725-0671431b-37af-4055-a271-5c8724fde7fa.png)

**Comment by mayfield** [comment]
That's what I expected.  They are rolling out a React based version of the activity widget in the dashboard feed.  Most likely themeing for the feed will have to be disabled.  I may have to abandon themes entirely as Strava continues to migrate to React which depending on their webpack build settings is completely non-extensible.  React is generally a disease for web extensions. :cry: 

These changes haven't made it to north america yet, so I can't even start to do the dev work to try and mitigate or disable themeing.  In the mean time can you share any other pages that are affected by this and expand on the issue of not being able to use the default theme?

**Comment by GoustiFruit** [comment]
Only the dashboard feed is affected AFAIK (I'm not Premium member, so I don't have access to some pages/features). Oh, the "Challenges" page is also "unthemed":
![2021-07-28 20 21 01 www strava com 5e45faf0c997](https://user-images.githubusercontent.com/52235969/127375522-303e8718-e242-4f5e-9cf6-1bd13f3efe80.png)

I guess that theming is not the most important feature of Sauce (though I like it ;-)): BTW, it's a great extension, very good job !
You know, nowadays, there are a several options (extensions) that give control to users to theme the websites they visit most often. So, it's incidental to implement it in a third-part extension.

**Comment by mayfield** [comment]
Thank you.  As soon as the rollout reaches me I'll start working on mitigation.

**Comment by mayfield** [comment]
This finally reached my region/account.  I'll can work on this now.

**Comment by GoustiFruit** [comment]
Nice. That you can now work on it. Not that it reached your region :-p

Le jeu. 5 août 2021 à 04:50, Justin Mayfield ***@***.***> a
écrit :

**Comment by mayfield** [comment]
Fixes rolling out now. Thank you @GoustiFruit

**Comment by GoustiFruit** [comment]
I can finally read the page :-) Thanks !
