### ISSUE TITLE
Run TSS is different on activity view vs fitness tracking view

### ISSUE THREAD

**Issue by pete911** [SauceLLC/sauce4strava#181]
When I go to run activity, TSS is much higher than TSS that is displayed in Fitness Tracking view.

## Activity view (47 TSS)

<img width="518" alt="activity" src="https://github.com/SauceLLC/sauce4strava/assets/567823/d968d0d9-d0a5-4eb7-aa9c-ead89ea2a83f">

## Fitness Tracking view (34 TSS)

<img width="500" alt="fitness-tracking" src="https://github.com/SauceLLC/sauce4strava/assets/567823/d72753d5-63d4-4b11-adbd-667eb9de9a6c">

**Comment by mayfield** [comment]
Hi @pete911 is it possible the run watts settings between the Sauce Options and your activity sync are different?  I assume this is from a Garmin watch that supports Garmins new "run power" and either your profile or the sauce options has run watts disabled, but not both.

**Comment by pete911** [comment]
Hi @mayfield, when I enabled run watts data in sauce options (it was disabled before), activity view went from 47 TSS to 87 TSS (difference is even higher). I am not sure where to disable running watts in strava settings ... but it doesn't look like this was the issue ...

**Comment by mayfield** [comment]
@pete911 can you email me, support@sauce.llc, the activity URL in question along with a screenshot of your sync panel settings and another of the Sauce Options (its in the Sauce Menu (top right drop down of most pages) or the the browser's options page for the Sauce for Strava Extention.

You can put them here if don't mind too.

**Comment by YetAnotherDickwall** [comment]
Same with me. 
 

https://www.strava.com/activities/10445357721 

![image](https://github.com/SauceLLC/sauce4strava/assets/34890065/526a7ae3-2b8b-46c2-8795-19a91bf26687)

![image](https://github.com/SauceLLC/sauce4strava/assets/34890065/e391a134-ce1d-4fd6-8670-c052fa59ddd1)


Watch is a Fenix 3. Just new to me but bought of ebay.

**Comment by pete911** [comment]
@mayfield, sure I'll send it later this week. I just noticed TSS is different for cycling as well (looks like it happened recently). On activity view TSS seems to be correct, on fitness tracking view it is much lower.

**Comment by pete911** [comment]
Hi @mayfield, I went for another run today, the same problem, but I made it worked by:
**Main sauce options** (under profile)
 [x] disable run watts data

**Activity sync options**
 [ ] disable run watts data (this effects cycling TSS not run TSS!)
 [x] estimated run power

- enabling run watts data in the main sauce options almost doubles activity page TSS
- enabling run watts data in activity sync options does NOT have any effect on run, but reduces cycling TSS
- enabling estimated run power in activity sync makes run TSS the same as disabling run watts data in main sauce options

Is there a but in activity sync options? Link for today's run is https://www.strava.com/activities/10467894021
