### ISSUE TITLE
Wrong FTP sync

### ISSUE THREAD

**Issue by johnpz91** [SauceLLC/sauce4strava#182]
Hi,

I'm getting a wrong FTP sync on all my past activities. FTP last know value (and past too) is off by a watt compared to my input on Strava.

Weight seems to be correct.

I tried clearing the cache, manually adjusting the last know value but it didn't work. 

thanks

**Comment by mayfield** [comment]
Hi @johnpz91 Can you email me some screenshots of the discrepencies you're seeing along with links to some of the activities in question.  support@sauce.llc
