### ISSUE TITLE
Not all activities are syncing on Activity Syncing on Strava Sauce 

### ISSUE THREAD

**Issue by plubelski** [SauceLLC/sauce4strava#189]
I am currently trying to sync all my activities on Strava sauce but in the Activity Sync part of the page it says that 202 activities are "Unavailable". Could someone explain why this is and if/how it can be fixed? Thanks

**Comment by mayfield** [comment]
Unavailable usually means the activity doesn't have streams, like a manual workout.  But it could also mean the activity was once seen during an activity scan but then not seen on a subsequent scan.  Such as in the case if the activity was deleted or it's privacy settings were changed.

**Comment by BT0123** [comment]
I have the same issue, since I cancelled my Strava mebmership. Is a membership at Strava mandatory for the sync af all activities?

**Comment by mayfield** [comment]
@BT0123 Strava membership isn't required.  You are more likely running into #210 

Try and update your extension in the Extensions settings (enable Developer Mode) and see if that helps.  If not, send me an email with your sync logs file to support@sauce.llc
