### ISSUE TITLE
Coments problem.

### ISSUE THREAD

**Issue by i-marszi** [SauceLLC/sauce4strava#19]
Does not display "Event Discussion"
In both chrome and firefox.
Mentioning in comments using @ did not work

**Comment by mayfield** [comment]
HI @i-marszi can you expand on what you mean by "Event Discussion"  Possibly with a link to an activity and/or pictures of what you mean?

I'll look into adding @ mention support.  At the time I authored the comment box they didn't support mentions in the web.  Looks like it's possible now though.  I'll make a separate issue for that.

**Comment by i-marszi** [comment]
This page:
https://www.strava.com/clubs/581770/group_events/915898
It should look like this:
![Screenshot_3](https://user-images.githubusercontent.com/17333265/112688785-9e1fc000-8e79-11eb-89e3-0d17293a6d67.png)

And it looks like this:
![Screenshot_2](https://user-images.githubusercontent.com/17333265/112688801-a415a100-8e79-11eb-9ab8-9b8ff436d5ed.png)

**Comment by mayfield** [comment]
@i-marszi Perfect thank you.  I've honestly never seen this page! :smile:

Hopefully an easy fix.  I can see the error in the console.  

Thank you!

**Comment by mayfield** [comment]
@i-marszi Published `v7.1.1` to the Firefox store with this fix.  Chrome will have to wait a little bit longer as it requires a longer testing cycle.

Thanks for the report!

**Comment by i-marszi** [comment]
WOW, great support :)
