### ISSUE TITLE
No Peak Power Data

### ISSUE THREAD

**Issue by xiaoxfan** [SauceLLC/sauce4strava#199]
Thank you for your selfless open-source contribution; it's truly an amazing project. I noticed that peak power and other power data cannot be displayed during my use. Do I need to subscribe to Strava Premium to view this data?
![image](https://github.com/user-attachments/assets/c9d3b46c-7239-4957-8b49-84307fbcb979)
![image](https://github.com/user-attachments/assets/13cbd76b-43ab-495d-997c-9876e7d8bb86)

**Comment by mayfield** [comment]
It looks like the estimated power data is not present on the activity.  I wasn't aware of Strava making that feature tied to their premium tier though.  Can you email me the activity in question so I can look at it?  support@sauce.llc
