### ISSUE TITLE
Pw:Hr in sauce / Microsoft Edge not visible

### ISSUE THREAD

**Issue by Riderrunner** [SauceLLC/sauce4strava#207]
Hi guys,

since yesterday (or Friday - i don't know it exactly) in Sauce (Microsoft Edge v130.0.2849.46) the value for Pw:Hr is not visible.
I can't find a setting to bring back that value....

Is there a way to bring back that value?

Thanks

**Comment by mayfield** [comment]
Hi,

Is it possibly hidden in the expanded information?
[image: image.png]

If you have TSS and tTSS showing it might be the 4th item which will only
show up when the analysis stats are expanded..

[image: image.png]

**Comment by Riderrunner** [comment]
Hi,

in my case it looks like as shown in the pic. In firefox it looks like it was before in Edge. 

![PwHr](https://github.com/user-attachments/assets/7090ea7e-b1c5-43e1-a3c1-e59ea2cd7a5b)

**Comment by mayfield** [comment]
Yeah, it should be visible if you click the expander.  The newer version (only available on chrome so far) shows both TSS (power based) and tTSS (HR based) when available, which will bump Pw:HR down one line (below the compressed analysis stats view cutoff).

**Comment by Riderrunner** [comment]
Ohoooo NOW i see the expand-option :-) thanks
