### ISSUE TITLE
Activity Sync of today's activities are not showing up in Fitness Tracking nor Peak Performance

### ISSUE THREAD

**Issue by sir-bmfw** [SauceLLC/sauce4strava#210]
Uploaded a couple of activities today and, despite manually refreshing and reuploading they are not showing up in either of the two performance pages. I am seeing Power/IF/TSS activity stats as well as 90 D best effort labels in Peak Pace on the Strava activity page; it looks like there's a break between the individual activity and including it in performance history.

**Comment by mayfield** [comment]
Hi @sir-bmfw can pull up the Activity Sync window, download the sync logs and email me that file to support@sauce.llc?

**Comment by HeyJey95** [comment]
Hi,
I am having the same problem.
Had a Zwift Workout yesterday and the activity is imported into Strava, but its not recognised by sauce in the activity tracker.
also the Activity Sync does not seem to miss it:
![image](https://github.com/user-attachments/assets/2fa13ed5-1946-46ed-a6b2-bbfffbce4239)

Kind Regards
J

**Comment by mayfield** [comment]
UPDATE: Strava did roll out a breaking change to one of the APIs I use.  It will most likely affect firefox users (long story), so if you're on firefox, try updating your add-ons now to get v8.4.4.1 that I just released.

**Comment by sir-bmfw** [comment]
Sounds good, thanks!

**Comment by mayfield** [comment]
Fixed with fabcde02ef2135e26039f0fbaa285b5c5346c669
