### ISSUE TITLE
Current Activities Not Syncing

### ISSUE THREAD

**Issue by scs-ben** [SauceLLC/sauce4strava#211]
My last activity to sync was from October 28. I think it's possible that with ongoing changes that something was updated that doesn't allow new activities to be imported.

**Comment by mayfield** [comment]
Yeah, Strava made some breaking changes to the training activity API.   I'm simultaneously doing a slow rollout of the new "v3 manifest" based sauce extension on the chrome web store which is a high risk update, so it's only set up to trickle out right now.

 * Firefox users should be good to go now (as of a couple days ago).  Look for version 8.4.4+
 * Chromium (including edge) users can force an update to v8.6.2+:
  1. Go to chrome://extensions
  2. Enable "Developer mode"
  3. Click "Update"
  4. Reload any strava tabs currently open.

**Comment by scs-ben** [comment]
Thanks! Updating in Chrome worked to get the missing activities in. It seems the sync got stuck on the last activity and just keep looping around with it (although that's not pertinent to this issue)

**Comment by mayfield** [comment]
Can you email me your sync logs (support@sauce.llc).  Look for a new download icon in the Activity Sync panel by the Logs section.

**Comment by scs-ben** [comment]
I stopped/restarted the sync and it finished running

**Comment by mayfield** [comment]
I'd actually still like to see your logs if that's possible.  Other than having to fetch activity history which takes 1 to 3 mins usually it should be flawless, so there might be new bug.

**Comment by scs-ben** [comment]
I emailed it

**Comment by rayherzog** [comment]
Same issue here. restarted the sync process several times and it is just stuck, never finishing...

**Comment by mayfield** [comment]
Tracked fix with original issue #210
