### ISSUE TITLE
Rank badge not visible in Activity Analysis

### ISSUE THREAD

**Issue by alexcolo** [SauceLLC/sauce4strava#217]
Hey, when I'm making an activity analysis I always saw the rank badge (Rank 4,3,2,1, Word Tour). since last update I'm missing it. I'm using Chrome.
![image](https://github.com/user-attachments/assets/5ea20ec6-6263-4a52-aa9e-7437517404a1)

**Comment by mayfield** [comment]
v8.7.2 should fix this.  It's rolling out now.  Thanks @alexcolo
