### ISSUE TITLE
Safari Kudo all not working on Mac or iPhone browsers

### ISSUE THREAD

**Issue by Sauceuser** [SauceLLC/sauce4strava#223]
Hadn't use the function in a while but have tried multiple times last few days, including on my iPhone. It pops up immediately with an everything Kudoed message, but none have been. Mac safari version is: Version 17.6 (19618.3.11.11.5) and iPhone 
version is 17.7

**Comment by mayfield** [comment]
Hi this is related to #219 

As soon as Strava calms down with updates I'll undertake a Safari (and firefox) release with the fixes.
