### ISSUE TITLE
Perf predictor missing

### ISSUE THREAD

**Issue by Artus44n** [SauceLLC/sauce4strava#230]
Hello,
Since few months the perf predictor missing. First i tought it was just removed or maybe became a premium feature. But a friend told me he can still use it so i guess there's a problem with my computer only ?
Tried on microsoft edge, private and on other google account. Nothing change.

If someone has a solution
Thanks

![image](https://github.com/user-attachments/assets/e290e5b5-5498-49d9-b44a-0cf6b620d517)

**Comment by mayfield** [comment]
Hi click the orange expander row and you'll see it.
