### ISSUE TITLE
FTP displayed on run segments is Cycling FTP

### ISSUE THREAD

**Issue by gcp** [SauceLLC/sauce4strava#28]
The display of NP / IF / TSS / FTP / Weight uses the cycling FTP (for the orange, adjustable display) even in run segments.

Changing the FTP there also changes the cycling FTP.

They should probably either not be displayed or split up between running/cycling.

**Comment by mayfield** [comment]
@gcp Sauce does actually compute power for runs based on weight.  Is the issue that you want to use different values between sports?  For me personally I've found them to be more or less the same.

**Comment by gcp** [comment]
They're very different for me, but that is comparing a Stryd to a bike power meter, which won't necessarily give comparable numbers so it's not relevant for the power estimates on Sauce (Strava unfortunately strips Stryd data, so there's no running power in my Strava data).

Overall I don't see any reason why running FTP would track bike FTP though. It's not like these evolve at the same moments during training.

**Comment by gcp** [comment]
If the time reference that Strava uses for pace zones is available to Sauce (i.e. say 20 min for a 5k), perhaps extrapolating those to a flat run, calculating the power (based on athlete weight), and then using that (after a % correction based on time) as the FTP would work.

Stryd seems to use 
1.5hr = 95% FTP
1hr = 98% FTP
45mins = 100% FTP
25mins = 103% FTP
20mins = 105% FTP
15mins = 106% FTP

**Comment by gcp** [comment]
As an example, my last 5k PR had 336W (according to Sauce's estimate) over 20 minutes. Using the conversion above, we'd arrive at a 320W running FTP.

This also means we'd estimate a 1 hour run at 313W should be possible.

Compare this to what happens now: Sauce uses my bike FTP (296W), sees an hour long run with a 310W average, and concludes it was at 105% IF, which is physiologically impossible!

**Comment by mayfield** [comment]
Thank you for the data @gcp 

In my case (mostly cyclist) my cycling numbers are more easily achieved.  I.e. I can RIDE at my FTP number more readily than I can RUN at the GAP pace that would result in the same power estimate.   So based on our two data points (which surely isn't enough for good science but something to consider), it does seem that different athletes can have different perceived exertions depending on sports and other personalized factors.

So I'll leave this issue open and try to consider how I can cleanly offer segmented FTP values for different sports.  My first thought is that it might make more sense to show FTP as peak 1 hour pace, and reverse out the power requirements (using the same sauce power est algo) for calculating things like TSS.   But I will have a LOT of UI work to implement something like this cleanly.  Especially with the new performance feature I've been working on (not yet public release).

**Comment by mayfield** [comment]
+1 from user support email: 
![image](https://user-images.githubusercontent.com/139316/141359075-6e8bfc69-5bc4-4244-8e41-f5df0f96bd92.png)

**Comment by Fabiocp85** [comment]
Any chance that we can simply exclude running power from peak charts for now? Running power has recently been added to Garmin watches (in beta phase, but is soon to be a public release), which means that lots of users will suddenly have power attached to their runs and this confusion of cycling power vs. running power will start affecting lots of people.
I don't want to disable power on my runs because eventually I would like to track progress, but I don't mind that it get excluded from peaks for now until we can find a permanent solution.

**Comment by mayfield** [comment]
Completed
