### ISSUE TITLE
Category Rank Not Working Properly

### ISSUE THREAD

**Issue by After1028** [SauceLLC/sauce4strava#29]
I've noticed just recently that the category rank (Ie: Cat 1, 2, 3, etc) seems to be a bit broken. The w/kg doesn't line up with the graph within Sauce that shows the where you measure up based on w/kg. It used to be correct but now it is off on all my activities. The picture I attached below is a ride I did the other day. For my 1 hour power I did 2.7 w/kg which would roughly be cat4/5 but Sauce is saying that it's actually Cat 3 which isn't correct.

<img width="484" alt="Screen Shot 2021-04-19 at 10 34 27 AM" src="https://user-images.githubusercontent.com/82824711/115254237-27ce5080-a0fb-11eb-96c6-026be9252119.png">

**Comment by mayfield** [comment]
I switched to using NP which is why it's not correlated exactly.  I'm on the fence about this for shorter efforts but it helps with ranking 1hour+ efforts dramatically.  

In either case, I do agree the badge needs to have a better tooltip showing the exact value being used.  Any thoughts @After1028 ?

**Comment by After1028** [comment]
> I switched to using NP which is why it's not correlated exactly. I'm on the fence about this for shorter efforts but it helps with ranking 1hour+ efforts dramatically.
> 
> In either case, I do agree the badge needs to have a better tooltip showing the exact value being used. Any thoughts @After1028 ?

**Comment by mayfield** [comment]
Gonna leave this open for tracking.  I do think improvements need to be made.

**Comment by After1028** [comment]
Sorry about closing that. I'm new to using Github, still trying to figure out how it works.

The normalized power makes sense, especially for the longer efforts like you said. How does NP work for shorter efforts (ie: sub 1 minute)? It seems like a lot of calculations use a 30 second rolling avg.

**Comment by mayfield** [comment]
No worries.

NP is only used for 5+ mins,  Coggan suggests 20+mins but everyone seems to use it for short stuff now.  I have considered changing the algo to only use NP when the duration is over an hour which would have prevented the confusion in your case.  But I'll still need to improve the UX to explain what figure is being used and when.

**Comment by mayfield** [comment]
![image](https://user-images.githubusercontent.com/139316/116160769-dea86e80-a6af-11eb-9ced-a769c447f2b9.png)

More notes..

A search for Peak  NP will yield better ranks than a search for just Peak Power because badges are always based on NP.   Ie. more confusion

**Comment by mayfield** [comment]
![PXL_20210426_233626909](https://user-images.githubusercontent.com/139316/116178249-7028d800-a6d2-11eb-9610-1fb6a4784baf.jpg)
