### ISSUE TITLE
Potential xPower error

### ISSUE THREAD

**Issue by i-marszi** [SauceLLC/sauce4strava#33]
Is it possible that the 5m xPower is smaller than the 10m xPower?
https://www.strava.com/activities/5549271178
5m xPower 255W
10m xPower 267W

**Comment by mayfield** [comment]
Hi @i-marszi 

xPower is an exponential weighted algorithm, so in some situations this IS possible.   My guess is that there is some high values followed by low (or zero) readings that are near the end of the 10 minute max period but not the 5 minute period.

Please re-open if this is not the case.
