### ISSUE TITLE
Search button misaligned

### ISSUE THREAD

**Issue by moogle19** [SauceLLC/sauce4strava#37]
When Sauce is activated on Firefox, the search button moves behind the Strava logo.
<img width="668" alt="Screenshot 2021-09-12 at 19 59 46" src="https://user-images.githubusercontent.com/792046/132997932-405efa5a-65a6-48e2-947e-60ac745a71bb.png">

**Comment by mayfield** [comment]
Confirmed regression from upstream change.

Only for responsive mode.
