### ISSUE TITLE
Export GPX from Segments

### ISSUE THREAD

**Issue by mikebarkmin** [SauceLLC/sauce4strava#38]

**Comment by mayfield** [comment]
Hi @mikebarkmin this is possible in a round about way currently.  You can select the segment then click the "Analyze" button which will open the analysis page with the segment's start/end selected.  Then from the sauce bar (must be expanded) you can click "Export: GPX, ..."

If you already knew this and/or were looking for a more convenient way to do this let me know.  I don't personally have a use-case for using segment-GPX-export so it has not been high on my prios to improve or change the visibility but I'm all ears on how  this could be of use to others.
