### ISSUE TITLE
Allow manual entry of smoothing window size

### ISSUE THREAD

**Issue by AndrewDDavis** [SauceLLC/sauce4strava#41]
The new smoothing feature is *awesome* but it's really hard (or impossible?) to get some specific smoothing window sizes. E.g. about 5 or 6 seconds is the sweet spot I'm looking for, but the slider seems to only allow certain values: 0, 2, 4, 7, 9, 12, ... s.

It would be great to be able to click the window size value and manually enter a value (e.g. 5 s); alternatively, allowing more values at the low end with the current slider would work for me as well (e.g. any integer value of seconds up to 15, then 5 second jumps after that).

**Comment by mayfield** [comment]
+1

**Comment by mayfield** [comment]
I'm going to close this as you can use the keyboard or manual entry in the advanced panel.
