### ISSUE TITLE
Enhance Dark Mode Display of Club Tables

### ISSUE THREAD

**Issue by ph4r** [SauceLLC/sauce4strava#61]
![image](https://user-images.githubusercontent.com/23483137/146809348-6a688e40-ed97-4578-bf0e-99ba4d9b8e5a.png)
Many items on these tables are not readable in the current Dark Mode Theme (which gets so much else right).  ScreenCap is from Chrome

**Comment by mayfield** [comment]
Thank you @ph4r.  Should hopefully be an easy fix.
