### ISSUE TITLE
Request: Cumulative Zone Distribution Feature

### ISSUE THREAD

**Issue by jamesford007** [SauceLLC/sauce4strava#63]
Strava shows your zone distribution for a given ride on the analysis page under the **Zone Distribution** tab.

![image](https://user-images.githubusercontent.com/23556889/147178046-c0a2897d-0815-4e23-a7ef-9588b754f249.png)

I would like to be able to view my zone distribution across a number of rides. This would give some additional insight into training and could complement the existing TSS/Time/Distance information in the **Sauce Performance** page. Showing the daily cumulative zone distribution would work well in the **Activity Details** section.

![image](https://user-images.githubusercontent.com/23556889/147178921-0d7a0d24-76c5-4699-a2fa-9a1713c0adfb.png)

Showing the cumulative zone distribution over a period of time would work well as a separate graph under the TSS/Time/Distance graph.

![image](https://user-images.githubusercontent.com/23556889/147179160-8f2a8536-2935-47c9-969e-c9b31786b430.png)

**Comment by jamesford007** [comment]
![200w](https://user-images.githubusercontent.com/23556889/147179802-85a72ac9-935f-49e0-b10a-f603c2937449.gif)

**Comment by mayfield** [comment]
You make a compelling case..

**Comment by jamesford007** [comment]
![source](https://user-images.githubusercontent.com/23556889/147180565-5a31bcce-00c5-4a91-be8c-40ed16bf511c.gif)

**Comment by mayfield** [comment]
Added
