### ISSUE TITLE
Export compressed backup

### ISSUE THREAD

**Issue by ddddavidee** [SauceLLC/sauce4strava#85]
Hi, 
I suggest to implement the export of a compressed file as backup. 
I use several browsers on several pc and used only one for the initial very loooooong sync, I then exported the data and imported on the others. The binary file is actually a pure json file, it could be a better idea to compress it and uncompress when importing the data.
In my case the ratio is quite high: ~200mega when uncompressed vs ~30mega when compressed (with 7z)

**Comment by ddddavidee** [comment]
Thank you for the quick reply.
I'm sorry, I am not familiar with browser extension development and approval process. 
I add this one as ref, but probably the issue you highlighted still stand with this one: https://github.com/dfrankland/wasm-brotli

**Comment by mayfield** [comment]
I believe `zip.js` was the one I had tried before.  It made the export process an order of magnitude slower. :) I'll checkout the brotli package.  Thanks @ddddavidee !
