### ISSUE TITLE
Missing from Firefox/Mozilla Add-On "Store"

### ISSUE THREAD

**Issue by eprowe** [SauceLLC/sauce4strava#98]
After reinstalling Windows I went to reinstall Sauce for Firefox and it's no longer listed in the add-ons repository.  I used the following link: [https://addons.mozilla.org/en-US/firefox/addon/sauce4strava/](https://addons.mozilla.org/en-US/firefox/addon/sauce4strava/)

Receive Mozilla's "Oops! We can’t find that page" error page.

**Comment by mayfield** [comment]
Waiting for them to approve a release.  I moved a couple files into a folder called lib and they lost their minds.  The add-on admin's have told me it would likely be resolved soon but that was several days ago and they've been unresponsive.  It's in a wait and see mode, but I'm not optimistic.  It's been very frustrating.

**Comment by eprowe** [comment]
No worries!  Thought it might be something on me end, or worse, something the team wasn't aware of.  As long as you know it's an issue and it's being worked on!  Thanks for all your hard work.

**Comment by mayfield** [comment]
Thank @eprowe.  I'll update this issue with any status updates.

**Comment by mayfield** [comment]
Got a new rejection this morning! Yay!

********
Details:
We have built your add-on on Ubuntu 18.04 using node 14.16.1, npm 6.14.12, but the resulting code is different from the one in the add-on version. You can access our build from https://we.tl/t-ruSzhCH7eW (Link expires in 7 days).
Also, please test your build in a clean environment to make sure it is reproducible. If necessary, update the source package and/or the instructions to build.

Version(s) affected:
8.0.7.1
********

The only difference I found in their build artifacts was the `build.json` file which is the git_commit in the git repo at the time of the build.  It is of course nonfunctional and just shows up for triage purposes.  I'd love to have them build from the git repo, but they don't support that! Ha!

```diff
:; diff -ur sauce-gecko-8.0.7.1-0/ ff-sauce/
diff -ur sauce-gecko-8.0.7.1-0/build.json ff-sauce/build.json
--- sauce-gecko-8.0.7.1-0/build.json	2022-03-15 03:43:39.000000000 -0600
+++ ff-sauce/build.json	2022-03-11 15:04:13.000000000 -0700
@@ -1 +1 @@
-{"git_commit": "0"}
+{"git_commit": "05290babbb22033ae30872f7aec764df44a1dbfd"}
```

Wrote back to clarify if this is the "difference" they are complaining about.  Expecting a response in 1 to 3 days.

**Comment by mayfield** [comment]
Surprisingly they approved it.  No comments though, so I don't know if I just convinced them or they realized they were in error.  Pretty sure they're robots actually.
