### ISSUE TITLE
Peak pace calculation error?

### ISSUE THREAD

**Issue by paulshrimpton-BC** [SauceLLC/sauce4strava#99]
Got some oddities here. Noticed this on several runs. Specific example:
Peak Pace over 10km = 5:46/km

Select Analysis:
Pace by the Sauce bottle = 4:49/km
Avg pace in the graph = 5:38/km

I think maybe 'elapsed time' is messing it up, because there were several stops???

![peak pace](https://user-images.githubusercontent.com/52052148/159037166-1d61b612-00b4-42a7-917f-5fad00784330.png)

**Comment by mayfield** [comment]
This looks like it's active time vs elapsed time.  The Peak table always uses elapsed time so records are not over inflated, but most other contexts use active time.

Feel free to reopen if I'm missing something.
